Update OrangeFox-Recovery-Builder.yml

diff --git a/.github/workflows/OrangeFox-Recovery-Builder.yml b/.github/workflows/OrangeFox-Recovery-Builder.yml
--- a/.github/workflows/OrangeFox-Recovery-Builder.yml
+++ b/.github/workflows/OrangeFox-Recovery-Builder.yml
@@ -100,6 +100,24 @@ jobs:
     - name: Build OrangeFox
       run: |
         cd ~/fox
+        # Принудительно подгружаем переменные Лисы
+        [ -f sync.sh ] && source sync.sh 
+        source build/envsetup.sh
+        
+        # Флаги, без которых Лиса не соберется в Boot
+        export ALLOW_MISSING_DEPENDENCIES=true
+        export FOX_REPLACE_BOOT_IF_NO_RECOVERY=1
+        export FOX_BUILD_DEVICE=WP15
+        export LC_ALL=C
+        
+        lunch omni_WP15-eng || { echo "LUNCH FAILED"; exit 1; }
+        
+        # Сначала соберем саму структуру рекавери
+        mka recoverytarball -j$(nproc --all)
+        # А теперь упакуем это в бут
+        mka bootimage -j$(nproc --all)
+
+        cd ~/fox
         source build/envsetup.sh
         
         # ОСНОВНЫЕ ФЛАГИ ORANGEFOX
